added faq dropdown component
HackBeanpot/core pull request #20
Opened 2024-11-24 23:30 UTC by agonzalez22

Added the dropdown component with spinning animations for icons
![image](https://github.com/user-attachments/assets/1b13a355-0fc3-46bc-84eb-efd09d931cfc)
![image](https://github.com/user-attachments/assets/40ba578d-5f3b-4d22-8dd1-3ac60f607944)

2024-11-28 21:18 UTC, nelson-dong requested changes
<img width="1808" alt="image" src="https://github.com/user-attachments/assets/ef862dbe-f07f-4941-9724-feb2707ab088">
 text explodes when too long!

2024-11-28 21:18 UTC, nelson-dong commented on packages/ui/src/FAQDropdown.tsx
> +    setIsOpen(!isOpen);
for better code practices use the callback for the state change
```setIsOpen((prevIsOpen) => !prevIsOpen);```

there is some weird state stuff with react where sometimes the state of isOpen is not always up to date at the right time. using the callback version ensures that you always have the right state.

2024-11-28 21:21 UTC, nelson-dong commented on packages/ui/package.json
> +    "@emotion/react": "^11.13.5",
not sure but are all of these dependencies for MUI neccessary? Looks like you are only using it for the icons right now.

2024-12-03 00:50 UTC, NelsonDong41 commented on packages/ui/package.json
> +    "@emotion/react": "^11.13.5",
https://heroicons.com/

2024-12-03 02:06 UTC, NelsonDong41 commented on apps/main/src/app/(landing)/page.tsx
> +    "ANswejoidfjlsdkjfoweidjlksdfjklsdjflskjhfgksjdhglskdjfghslkdjfghslkdfjghskldjfghskldjfghsdkljfghsdlkfg";
remove before merge!

2024-12-03 02:07 UTC, NelsonDong41 requested changes

2024-12-03 02:07 UTC, NelsonDong41 commented on packages/ui/package.json
>    }
are these used now that icons are from tailwind

2024-12-03 02:07 UTC, NelsonDong41 commented on packages/ui/src/FAQDropdown.tsx
> +    <>
no need for wrapper fragment, div at top level wraps everything

2024-12-03 02:34 UTC, NelsonDong41 approved these changes

2024-12-03 02:34 UTC, NelsonDong41 commented on packages/ui/package.json
> +  "dependencies": {}
???!!

2024-12-03 02:34 UTC, NelsonDong41 commented on yarn.lock
> +    regenerator-runtime "^0.14.0"
yarn

2024-12-03 02:44 UTC, merged