Created Arrow Button Component
HackBeanpot/core pull request #21
Opened 2024-11-25 23:57 UTC by yumi520

Created the arrow button component with props for the background color of the button, left or right direction for the arrow, and color of the top border shadow.

![image](https://github.com/user-attachments/assets/4f0e0c35-3ebc-481d-87ac-410951bb923a)

![image](https://github.com/user-attachments/assets/92401217-3198-4d69-93e5-2460e3aaa4a7)

2024-11-30 05:30 UTC, NelsonDong41 requested changes

2024-11-30 05:30 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +        ) : (
move these into their own svgs!

```tsx
const LeftArrow = () => <svg .... />
const RightArrow = () => <svg ... />

{direction === 'left' ? <LeftArrow> : <RightArrow>}

```

2024-11-30 05:30 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +}
Every company does diff things but i think the consensus is not to use enums and always use types. In this case that means

```tsx
type ArrowType = "left" | "right"
```

this is for a few reasons but some are:

- now there is no need to import the ArrowType everywhere. Before if you used the arrow anywhere, you would also have to import ArrowType just to do, `<ArrowButton direction={ArrowType.left} />`. Now you can just write `<ArrowButton direction={'left'} />`
- It lets vscode autofill/intellisense the options easily, 
<img width="585" alt="image" src="https://github.com/user-attachments/assets/2ce9b619-8153-4cb4-84c4-0a4139db6de5">

2024-11-30 05:30 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +  topBorderColor,
maybe also add defaults for these, as well as types. This specifically because on figma, there seem to only be 2 use cases, beige or purple. That means you potentially don't even need to pass in the bg color or top border color. You can just have a field "ButtonType" which can be typed `"beige" | "purple"` and based on that you can find what color the component should be

2024-12-03 01:21 UTC, NelsonDong41 commented on apps/main/src/app/page.tsx
> +
is this required?

2024-12-03 01:28 UTC, NelsonDong41 requested changes

2024-12-03 01:28 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +};
move this to packages -> tailwind config -> design-tokens -> colors. Then from there, you can just use colors as like `text-green` or `bg-green`

2024-12-03 01:28 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +        }}
please use tailwind! https://stackoverflow.com/a/74959709 try this? If that doesnt work you can leave style as is!

2024-12-03 01:28 UTC, NelsonDong41 commented on packages/ui/src/ArrowButton.tsx
> +  topBorderColor = "darkPurple",
I like the idea but is there a need to define all 3 of these everytime i make an arrowbutton? Maybe only have 1 field `colorType` of type `beige, purple, green` and change the arrowColor, bgColor and topBorderColor based on that one field instead of all 3. Reasoning is that according to figma, there are only 3 different variations of this button. With this type of setup, you are allowing for 9 different configurations which is unnecesssary

2024-12-04 21:51 UTC, yumi520 commented on apps/main/src/app/page.tsx
> +
I remember there being an error if I didn't do that, should I remove it or is it fine? I'll try it again without it and see what happens

2024-12-11 01:16 UTC, NelsonDong41 approved these changes

2024-12-14 18:42 UTC, merged